_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 5
                - 11
                - 40
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 40
                - 41
                - 49
                - 53
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.18.7
            "6": 4.46.3
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
data:
    value:
        annotation_file: ../config/bedroom_threed_front_splits.csv
        augmentations:
            - fixed_rotations
        dataset_directory: /home/ubuntu/3d_front_processed/bedrooms_objfeats_32_64
        dataset_type: cached_threedfront
        encoding_type: cached_diffusion_cosin_angle_objfeatsnorm_lat32_wocm
        filter_fn: threed_front_bedroom
        path_to_invalid_bbox_jids: ../config/black_list.txt
        path_to_invalid_scene_ids: ../config/invalid_threed_front_rooms.txt
        room_layout_size: 64,64
        train_stats: dataset_stats.txt
feature_extractor:
    value:
        feature_size: 64
        freeze_bn: true
        input_channels: 1
        name: resnet18
logger:
    value:
        project: diffuscene
        type: wandb
network:
    value:
        angle_dim: 2
        class_dim: 22
        diffusion_kwargs:
            beta_end: 0.02
            beta_start: 0.0001
            loss_iou: true
            loss_separate: true
            loss_type: mse
            model_mean_type: v
            model_var_type: fixedsmall
            schedule_type: linear
            time_num: 1000
            train_stats_file: /home/ubuntu/3d_front_processed/bedrooms_objfeats_32_64/dataset_stats.txt
        instance_condition: true
        instance_emb_dim: 128
        latent_dim: 0
        learnable_embedding: true
        net_kwargs:
            angle_dim: 2
            channels: 62
            class_dim: 22
            context_dim: 0
            dim: 512
            dim_mults:
                - 1
                - 1
                - 1
                - 1
            instanclass_dim: 128
            objectness_dim: 0
            objfeat_dim: 32
            seperate_all: true
        net_type: unet1d
        objectness_dim: 0
        objfeat_dim: 32
        point_dim: 62
        room_mask_condition: false
        sample_num_points: 12
        type: diffusion_scene_layout_ddpm
training:
    value:
        batch_size: 512
        epochs: 60000
        lr: 0.0002
        lr_decay: 0.5
        lr_step: 10000
        max_grad_norm: 10
        optimizer: Adam
        save_frequency: 2000
        schedule: step
        splits:
            - train
            - val
        steps_per_epoch: 500
        weight_decay: 0
validation:
    value:
        batch_size: 128
        frequency: 10
        gen_gt: false
        gen_prob_map: false
        gen_traj: false
        num_step: 100
        splits:
            - test
